#ifdef COLOR
#undef COLOR
#undef DEPTH
#undef STENCIL
#undef DEPTH_STENCIL
#undef INITIAL_LAYOUT
#undef FINAL_LAYOUT
#endif

#ifndef INITIAL_LAYOUT_WRAPPER
#define INITIAL_LAYOUT_WRAPPER(l)
#endif

#ifndef FINAL_LAYOUT_WRAPPER
#define FINAL_LAYOUT_WRAPPER(l)
#endif

#ifndef COLOR_WRAPPER
#define COLOR_WRAPPER(...) WRAPPER(__VA_ARGS__)
#endif

#ifndef DS_WRAPPER
#define DS_WRAPPER(...) WRAPPER(__VA_ARGS__)
#endif

#ifdef WRAPPER
#define INITIAL_LAYOUT(l) INITIAL_LAYOUT_WRAPPER(l)
#define FINAL_LAYOUT(l) FINAL_LAYOUT_WRAPPER(l)

#define COLOR(name, load) COLOR_WRAPPER(name, VK_SAMPLE_COUNT_1_BIT, static_cast<VkAttachmentLoadOp>(load), VK_ATTACHMENT_STORE_OP_STORE, VK_ATTACHMENT_LOAD_OP_DONT_CARE, VK_ATTACHMENT_STORE_OP_DONT_CARE, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL)

#endif